# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d3e30cbe6eed6fe504f20f872b29bc5aefafee49616f309774bf44f16918c10d75ebacd9e334c9a498af67c54e703618c27ba6227442b8a87db5ab46af58ee8

test:
  secret_key_base: 8c5a2a0c50530a2a2102856109ed19589a70d1a76e0640505880ab0974393e70e26fa6373633397a0ba57dc803ffdc8b85a8f0eb34ead0f9bef3638ba13267b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
